### ISSUE TITLE
[FEATURE] Display episode number before title in next aired in LowList view

### ISSUE THREAD

**Issue by bernhardberger** [mikesilvo164/repo.aeon.nox.silvo#1]
Sorry for opening a ticket, but because of a forum glitch I can't post in the forums for the past weeks..

Regarding this:
http://forum.kodi.tv/showthread.php?tid=210069&pid=1954771#pid1954771

I ment in the sidebar in the entry (TV Show overview) level where the ***next aired*** info is displayed on the right side.

Currently only the title is displayed there, but it would be a massive enhancement if you could also ***prefix the line with the episode number*** so you always know where you're at. Also helps verifying if you may have missed an eposide.

PS: time info on recorded live tv would be big too ;-) Still willing to donate for your work if you've got some flattr or paypal account.

**Comment by mikesilvo164** [comment]
I have added the requested info to LowList next aired but I no longer have PVR on my machine (tuner card crapped out) so I cannot work on the PVR stuff till I replace it. I do not check this page often so for a more timely response post to the skin Git page instead. If you'd rather post here that's not a problem I just rarely check it.
